name: Publish Gem

on:
  release:
    types: [created]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"
          bundler-cache: true

      - name: Build Gem
        run: gem build *.gemspec

      - name: Publish to GitHub Packages
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
